### ISSUE TITLE
Exceptions in display mode

### ISSUE THREAD

**Issue by grosmar** [haxetink/tink_web#48] opened 2017-12-19 10:34 UTC
In display mode many times it appears the following exception:
`Main.hx:39: chars 9-36 : Error: MyData should be tink.web.routing.Response`

According to @back2dos :

> yeah, that's related to tink_web sometimes not working in display mode because the compiler seems to skip something for speed

**Comment by back2dos** [comment] 2019-02-21 13:44
Duplicate of #62

**Closed by back2dos** 2019-02-21 13:44 UTC
